activation: ReLU
alias: null
batch_size: 32
drop_last_loader: false
dropout_prob_theta: 0.0
early_stop_patience_steps: 10
exclude_insample_y: false
futr_exog_list: null
h: 12
hist_exog_list:
- month
inference_windows_batch_size: -1
input_size: 24
interpolation_mode: linear
learning_rate: 0.001
loss: !!python/object:neuralforecast.losses.pytorch.GMM
  _backward_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _backward_pre_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _buffers: !!python/object/apply:collections.OrderedDict
  - []
  _forward_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _forward_hooks_with_kwargs: !!python/object/apply:collections.OrderedDict
  - []
  _forward_pre_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _forward_pre_hooks_with_kwargs: !!python/object/apply:collections.OrderedDict
  - []
  _is_full_backward_hook: null
  _load_state_dict_post_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _load_state_dict_pre_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _modules: !!python/object/apply:collections.OrderedDict
  - []
  _non_persistent_buffers_set: !!set {}
  _parameters: !!python/object/apply:collections.OrderedDict
  - - - quantiles
      - !!python/object/apply:torch._utils._rebuild_parameter
        - !!python/object/apply:torch._utils._rebuild_tensor_v2
          - !!python/object/apply:torch.storage._load_from_bytes
            - !!binary |
              gAKKCmz8nEb5IGqoUBkugAJN6QMugAJ9cQAoWBAAAABwcm90b2NvbF92ZXJzaW9ucQFN6QNYDQAA
              AGxpdHRsZV9lbmRpYW5xAohYCgAAAHR5cGVfc2l6ZXNxA31xBChYBQAAAHNob3J0cQVLAlgDAAAA
              aW50cQZLBFgEAAAAbG9uZ3EHSwR1dS6AAihYBwAAAHN0b3JhZ2VxAGN0b3JjaApGbG9hdFN0b3Jh
              Z2UKcQFYDgAAADk0MzU1NzU2NTkzNDA4cQJYAwAAAGNwdXEDS2NOdHEEUS6AAl1xAFgOAAAAOTQz
              NTU3NTY1OTM0MDhxAWEuYwAAAAAAAAAK1yM8CtejPI/C9TwK1yM9zcxMPY/CdT0pXI89CtejPexR
              uD3NzMw9rkfhPY/C9T24HgU+KVwPPpqZGT4K1yM+exQuPuxROD5cj0I+zcxMPj0KVz6uR2E+H4Vr
              Po/CdT4AAIA+uB6FPnE9ij4pXI8+4XqUPpqZmT5SuJ4+CtejPsP1qD57FK4+MzOzPuxRuD6kcL0+
              XI/CPhSuxz7NzMw+hevRPj0K1z72KNw+rkfhPmZm5j4fhes+16PwPo/C9T5I4fo+AAAAP1yPAj+4
              HgU/FK4HP3E9Cj/NzAw/KVwPP4XrET/hehQ/PQoXP5qZGT/2KBw/UrgeP65HIT8K1yM/ZmYmP8P1
              KD8fhSs/exQuP9ejMD8zMzM/j8I1P+xROD9I4To/pHA9PwAAQD9cj0I/uB5FPxSuRz9xPUo/zcxM
              PylcTz+F61E/4XpUPz0KVz+amVk/9ihcP1K4Xj+uR2E/CtdjP2ZmZj/D9Wg/H4VrP3sUbj/Xo3A/
              MzNzP4/CdT/sUXg/SOF6P6RwfT8=
          - 0
          - !!python/tuple
            - 99
          - !!python/tuple
            - 1
          - false
          - !!python/object/apply:collections.OrderedDict
            - []
        - false
        - !!python/object/apply:collections.OrderedDict
          - []
  _state_dict_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _state_dict_pre_hooks: !!python/object/apply:collections.OrderedDict
  - []
  batch_correlation: false
  horizon_correlation: false
  is_distribution_output: true
  num_samples: 1000
  output_names:
  - ''
  - -lo-98.0
  - -lo-96.0
  - -lo-94.0
  - -lo-92.0
  - -lo-90.0
  - -lo-88.0
  - -lo-86.0
  - -lo-84.0
  - -lo-82.0
  - -lo-80.0
  - -lo-78.0
  - -lo-76.0
  - -lo-74.0
  - -lo-72.0
  - -lo-70.0
  - -lo-68.0
  - -lo-66.0
  - -lo-64.0
  - -lo-62.0
  - -lo-60.0
  - -lo-58.0
  - -lo-56.0
  - -lo-54.0
  - -lo-52.0
  - -lo-50.0
  - -lo-48.0
  - -lo-46.0
  - -lo-44.0
  - -lo-42.0
  - -lo-40.0
  - -lo-38.0
  - -lo-36.0
  - -lo-34.0
  - -lo-32.0
  - -lo-30.0
  - -lo-28.0
  - -lo-26.0
  - -lo-24.0
  - -lo-22.0
  - -lo-20.0
  - -lo-18.0
  - -lo-16.0
  - -lo-14.0
  - -lo-12.0
  - -lo-10.0
  - -lo-8.0
  - -lo-6.0
  - -lo-4.0
  - -lo-2.0
  - -median
  - -hi-2.0
  - -hi-4.0
  - -hi-6.0
  - -hi-8.0
  - -hi-10.0
  - -hi-12.0
  - -hi-14.0
  - -hi-16.0
  - -hi-18.0
  - -hi-20.0
  - -hi-22.0
  - -hi-24.0
  - -hi-26.0
  - -hi-28.0
  - -hi-30.0
  - -hi-32.0
  - -hi-34.0
  - -hi-36.0
  - -hi-38.0
  - -hi-40.0
  - -hi-42.0
  - -hi-44.0
  - -hi-46.0
  - -hi-48.0
  - -hi-50.0
  - -hi-52.0
  - -hi-54.0
  - -hi-56.0
  - -hi-58.0
  - -hi-60.0
  - -hi-62.0
  - -hi-64.0
  - -hi-66.0
  - -hi-68.0
  - -hi-70.0
  - -hi-72.0
  - -hi-74.0
  - -hi-76.0
  - -hi-78.0
  - -hi-80.0
  - -hi-82.0
  - -hi-84.0
  - -hi-86.0
  - -hi-88.0
  - -hi-90.0
  - -hi-92.0
  - -hi-94.0
  - -hi-96.0
  - -hi-98.0
  outputsize_multiplier: 20
  return_params: false
  training: true
max_steps: 2000
mlp_units:
- &id001
  - 512
  - 512
- *id001
- *id001
n_blocks:
- 1
- 1
- 1
n_freq_downsample:
- 4
- 2
- 1
n_pool_kernel_size:
- 2
- 2
- 1
num_lr_decays: 3
num_workers_loader: 0
pooling_mode: MaxPool1d
random_seed: 1
scaler_type: robust
stack_types:
- identity
- identity
- identity
stat_exog_list: null
step_size: 1
val_check_steps: 50
valid_batch_size: null
valid_loss: !!python/object:neuralforecast.losses.pytorch.sCRPS
  _backward_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _backward_pre_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _buffers: !!python/object/apply:collections.OrderedDict
  - []
  _forward_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _forward_hooks_with_kwargs: !!python/object/apply:collections.OrderedDict
  - []
  _forward_pre_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _forward_pre_hooks_with_kwargs: !!python/object/apply:collections.OrderedDict
  - []
  _is_full_backward_hook: null
  _load_state_dict_post_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _load_state_dict_pre_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _modules: !!python/object/apply:collections.OrderedDict
  - - - mql
      - !!python/object:neuralforecast.losses.pytorch.MQLoss
        _backward_hooks: !!python/object/apply:collections.OrderedDict
        - []
        _backward_pre_hooks: !!python/object/apply:collections.OrderedDict
        - []
        _buffers: !!python/object/apply:collections.OrderedDict
        - []
        _forward_hooks: !!python/object/apply:collections.OrderedDict
        - []
        _forward_hooks_with_kwargs: !!python/object/apply:collections.OrderedDict
        - []
        _forward_pre_hooks: !!python/object/apply:collections.OrderedDict
        - []
        _forward_pre_hooks_with_kwargs: !!python/object/apply:collections.OrderedDict
        - []
        _is_full_backward_hook: null
        _load_state_dict_post_hooks: !!python/object/apply:collections.OrderedDict
        - []
        _load_state_dict_pre_hooks: !!python/object/apply:collections.OrderedDict
        - []
        _modules: !!python/object/apply:collections.OrderedDict
        - []
        _non_persistent_buffers_set: !!set {}
        _parameters: !!python/object/apply:collections.OrderedDict
        - - - quantiles
            - !!python/object/apply:torch._utils._rebuild_parameter
              - !!python/object/apply:torch._utils._rebuild_tensor_v2
                - !!python/object/apply:torch.storage._load_from_bytes
                  - !!binary |
                    gAKKCmz8nEb5IGqoUBkugAJN6QMugAJ9cQAoWBAAAABwcm90b2NvbF92ZXJzaW9ucQFN6QNYDQAA
                    AGxpdHRsZV9lbmRpYW5xAohYCgAAAHR5cGVfc2l6ZXNxA31xBChYBQAAAHNob3J0cQVLAlgDAAAA
                    aW50cQZLBFgEAAAAbG9uZ3EHSwR1dS6AAihYBwAAAHN0b3JhZ2VxAGN0b3JjaApGbG9hdFN0b3Jh
                    Z2UKcQFYDgAAADk0MzU1ODY0NjE3ODU2cQJYAwAAAGNwdXEDS2NOdHEEUS6AAl1xAFgOAAAAOTQz
                    NTU4NjQ2MTc4NTZxAWEuYwAAAAAAAAAK1yM8CtejPI/C9TwK1yM9zcxMPY/CdT0pXI89CtejPexR
                    uD3NzMw9rkfhPY/C9T24HgU+KVwPPpqZGT4K1yM+exQuPuxROD5cj0I+zcxMPj0KVz6uR2E+H4Vr
                    Po/CdT4AAIA+uB6FPnE9ij4pXI8+4XqUPpqZmT5SuJ4+CtejPsP1qD57FK4+MzOzPuxRuD6kcL0+
                    XI/CPhSuxz7NzMw+hevRPj0K1z72KNw+rkfhPmZm5j4fhes+16PwPo/C9T5I4fo+AAAAP1yPAj+4
                    HgU/FK4HP3E9Cj/NzAw/KVwPP4XrET/hehQ/PQoXP5qZGT/2KBw/UrgeP65HIT8K1yM/ZmYmP8P1
                    KD8fhSs/exQuP9ejMD8zMzM/j8I1P+xROD9I4To/pHA9PwAAQD9cj0I/uB5FPxSuRz9xPUo/zcxM
                    PylcTz+F61E/4XpUPz0KVz+amVk/9ihcP1K4Xj+uR2E/CtdjP2ZmZj/D9Wg/H4VrP3sUbj/Xo3A/
                    MzNzP4/CdT/sUXg/SOF6P6RwfT8=
                - 0
                - !!python/tuple
                  - 99
                - !!python/tuple
                  - 1
                - false
                - !!python/object/apply:collections.OrderedDict
                  - []
              - false
              - !!python/object/apply:collections.OrderedDict
                - []
        _state_dict_hooks: !!python/object/apply:collections.OrderedDict
        - []
        _state_dict_pre_hooks: !!python/object/apply:collections.OrderedDict
        - []
        is_distribution_output: false
        output_names:
        - -lo-98.0
        - -lo-96.0
        - -lo-94.0
        - -lo-92.0
        - -lo-90.0
        - -lo-88.0
        - -lo-86.0
        - -lo-84.0
        - -lo-82.0
        - -lo-80.0
        - -lo-78.0
        - -lo-76.0
        - -lo-74.0
        - -lo-72.0
        - -lo-70.0
        - -lo-68.0
        - -lo-66.0
        - -lo-64.0
        - -lo-62.0
        - -lo-60.0
        - -lo-58.0
        - -lo-56.0
        - -lo-54.0
        - -lo-52.0
        - -lo-50.0
        - -lo-48.0
        - -lo-46.0
        - -lo-44.0
        - -lo-42.0
        - -lo-40.0
        - -lo-38.0
        - -lo-36.0
        - -lo-34.0
        - -lo-32.0
        - -lo-30.0
        - -lo-28.0
        - -lo-26.0
        - -lo-24.0
        - -lo-22.0
        - -lo-20.0
        - -lo-18.0
        - -lo-16.0
        - -lo-14.0
        - -lo-12.0
        - -lo-10.0
        - -lo-8.0
        - -lo-6.0
        - -lo-4.0
        - -lo-2.0
        - -median
        - -hi-2.0
        - -hi-4.0
        - -hi-6.0
        - -hi-8.0
        - -hi-10.0
        - -hi-12.0
        - -hi-14.0
        - -hi-16.0
        - -hi-18.0
        - -hi-20.0
        - -hi-22.0
        - -hi-24.0
        - -hi-26.0
        - -hi-28.0
        - -hi-30.0
        - -hi-32.0
        - -hi-34.0
        - -hi-36.0
        - -hi-38.0
        - -hi-40.0
        - -hi-42.0
        - -hi-44.0
        - -hi-46.0
        - -hi-48.0
        - -hi-50.0
        - -hi-52.0
        - -hi-54.0
        - -hi-56.0
        - -hi-58.0
        - -hi-60.0
        - -hi-62.0
        - -hi-64.0
        - -hi-66.0
        - -hi-68.0
        - -hi-70.0
        - -hi-72.0
        - -hi-74.0
        - -hi-76.0
        - -hi-78.0
        - -hi-80.0
        - -hi-82.0
        - -hi-84.0
        - -hi-86.0
        - -hi-88.0
        - -hi-90.0
        - -hi-92.0
        - -hi-94.0
        - -hi-96.0
        - -hi-98.0
        outputsize_multiplier: 99
        training: true
  _non_persistent_buffers_set: !!set {}
  _parameters: !!python/object/apply:collections.OrderedDict
  - []
  _state_dict_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _state_dict_pre_hooks: !!python/object/apply:collections.OrderedDict
  - []
  is_distribution_output: false
  training: true
windows_batch_size: 1024
